# Site settings
title: Philip Clarke
description: PhD student
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Philip Clarke
user_description: I\'m currently finishing a PhD in early universe cosmology, at the University of Cambridge. I enjoy physics, coding and communication, sometimes all at the same time.
user_title: PhD student
email: clarkeph@tcd.ie
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
